### ISSUE TITLE
Don't resolve project dependencies using metal-cli's node_modules as root

### ISSUE THREAD

**Issue by izaera** [metal/babel-preset-metal-resolve-source#1]
Currently the `resolve` function is trying to resolve dependencies on the context of the tool (metal-cli) instead of on the context of the scanned process. This leads to metal-cli including incorrect dependencies when transpiling modules.

For instance, try to include isobject as a dependency in a metal-cli enabled project and you will get the isobject from metal-cli instead of the one from your project.

**Comment by eduardolundgren** [comment]
@izaera I remember @mairatma mentioning that our babel preset were deprecated. Could you please check if it's still being used or necessary? Thanks.

**Comment by izaera** [comment]
It is used, indeed. It is being invoked by metal-cli when running gradle on a blade type project. It is possible that overriding module versions in package.json it stops being used. I'll check that...

**Comment by mairatma** [comment]
If I remember correctly, it still needs to be used for the globals build, both on metal-cli and gulp-metal. When using a third party tool like browserify, webpack or rollup it's not necessary though, you can just use `babel-preset-metal` directly. So basically if metal-cli and gulp-metal can be updated to use one of these three I've mentioned, we could get rid of this package.

**Comment by izaera** [comment]
BTW, note that I will send a pull on Monday fixing this @eduardolundgren. It's just that I haven't had time today.
